package main

// ---------------------------------------------------------------------------
// cmd_help.go — per-command help text
// ---------------------------------------------------------------------------

import (
	"fmt"
	"os"
)

func cmdHelp(subcmd string) {
	switch subcmd {
	case "up":
		fmt.Printf("%s\n\n", bold("1sec up"))
		fmt.Printf("Start the 1SEC engine with all enabled modules.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--config <path>", "Config file (default: configs/default.yaml, env: ONESEC_CONFIG)")
		fmt.Printf("  %-28s  %s\n", "--modules <list>", "Comma-separated list of modules to enable (disables all others)")
		fmt.Printf("  %-28s  %s\n", "--log-level <level>", "Log level: debug, info, warn, error (default: from config)")
		fmt.Printf("  %-28s  %s\n", "--dry-run", "Validate config and modules, then exit without starting")
		fmt.Printf("  %-28s  %s\n", "-q, --quiet", "Suppress banner and non-essential output")
		fmt.Printf("  %-28s  %s\n", "--no-color", "Disable color output")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec up\n")
		fmt.Printf("  1sec up --config /etc/1sec/prod.yaml\n")
		fmt.Printf("  1sec up --modules injection_shield,auth_fortress\n")
		fmt.Printf("  1sec up --log-level debug\n")
		fmt.Printf("  1sec up --dry-run\n")
	case "status":
		fmt.Printf("%s\n\n", bold("1sec status"))
		fmt.Printf("Fetch and display the status of a running 1SEC instance.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--config <path>", "Config file to derive API address")
		fmt.Printf("  %-28s  %s\n", "--host <host>", "API host (overrides config, env: ONESEC_HOST)")
		fmt.Printf("  %-28s  %s\n", "--port <port>", "API port (overrides config, env: ONESEC_PORT)")
		fmt.Printf("  %-28s  %s\n", "--api-key <key>", "API key (env: ONESEC_API_KEY)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json, csv (default: table)")
		fmt.Printf("  %-28s  %s\n", "--json", "Shorthand for --format json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use (env: ONESEC_PROFILE)")
		fmt.Printf("  %-28s  %s\n", "--output <file>", "Write output to file instead of stdout")
		fmt.Printf("  %-28s  %s\n", "--timeout <duration>", "Request timeout (default: 5s)")
	case "alerts":
		fmt.Printf("%s\n\n", bold("1sec alerts"))
		fmt.Printf("Fetch, acknowledge, resolve, or clear alerts from a running 1SEC instance.\n\n")
		fmt.Printf("%s\n\n", bold("SUBCOMMANDS"))
		fmt.Printf("  %-20s  %s\n", "ack <id>", "Acknowledge an alert")
		fmt.Printf("  %-20s  %s\n", "resolve <id>", "Mark an alert as resolved")
		fmt.Printf("  %-20s  %s\n", "false-positive <id>", "Mark an alert as false positive")
		fmt.Printf("  %-20s  %s\n", "get <id>", "Get a specific alert by ID")
		fmt.Printf("  %-20s  %s\n", "delete <id>", "Delete a specific alert by ID")
		fmt.Printf("  %-20s  %s\n", "clear", "Remove all stored alerts")
		fmt.Printf("\n%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json, csv, sarif")
		fmt.Printf("  %-28s  %s\n", "--severity <level>", "Minimum severity: INFO, LOW, MEDIUM, HIGH, CRITICAL")
		fmt.Printf("  %-28s  %s\n", "--module <name>", "Filter alerts by source module")
		fmt.Printf("  %-28s  %s\n", "--status <status>", "Filter by status: OPEN, ACKNOWLEDGED, RESOLVED, FALSE_POSITIVE")
		fmt.Printf("  %-28s  %s\n", "--limit <n>", "Maximum number of alerts (default: 20)")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec alerts\n")
		fmt.Printf("  1sec alerts --severity HIGH --format sarif\n")
		fmt.Printf("  1sec alerts --format csv --output alerts.csv\n")
		fmt.Printf("  1sec alerts ack abc-123-def\n")
		fmt.Printf("  1sec alerts resolve abc-123-def\n")
		fmt.Printf("  1sec alerts delete abc-123-def\n")
	case "scan":
		fmt.Printf("%s\n\n", bold("1sec scan"))
		fmt.Printf("Submit a payload for on-demand analysis by a running 1SEC instance.\n")
		fmt.Printf("Reads from stdin or a file, sends it as a SecurityEvent to the event bus.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--module <name>", "Module to attribute the event to (default: external)")
		fmt.Printf("  %-28s  %s\n", "--type <type>", "Event type (default: scan)")
		fmt.Printf("  %-28s  %s\n", "--severity <level>", "Event severity (default: MEDIUM)")
		fmt.Printf("  %-28s  %s\n", "--input <file>", "Read payload from file instead of stdin (use - for stdin)")
		fmt.Printf("  %-28s  %s\n", "--wait", "Wait for analysis results after submission")
		fmt.Printf("  %-28s  %s\n", "--wait-timeout <duration>", "How long to wait for results (default: 30s)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  echo '{\"query\": \"1 OR 1=1\"}' | 1sec scan --module injection_shield\n")
		fmt.Printf("  1sec scan --input payload.json --module llm_firewall --wait\n")
		fmt.Printf("  curl -s https://example.com/api | 1sec scan --module api_fortress\n")
	case "modules":
		fmt.Printf("%s\n\n", bold("1sec modules"))
		fmt.Printf("List, inspect, enable, or disable defense modules.\n\n")
		fmt.Printf("%s\n\n", bold("SUBCOMMANDS"))
		fmt.Printf("  %-20s  %s\n", "info <name>", "Show detailed info about a specific module")
		fmt.Printf("  %-20s  %s\n", "enable <name>", "Enable a module in the config file")
		fmt.Printf("  %-20s  %s\n", "disable <name>", "Disable a module in the config file")
		fmt.Printf("\n%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json, csv")
		fmt.Printf("  %-28s  %s\n", "--tier <n>", "Filter by tier number (1-6)")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
	case "config":
		fmt.Printf("%s\n\n", bold("1sec config"))
		fmt.Printf("Show, validate, or modify the resolved configuration.\n\n")
		fmt.Printf("%s\n\n", bold("SUBCOMMANDS"))
		fmt.Printf("  %-20s  %s\n", "set <key> <value>", "Set a configuration value (dot-notation)")
		fmt.Printf("\n%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--validate", "Validate config and exit (exit 0 = valid)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec config\n")
		fmt.Printf("  1sec config --validate\n")
		fmt.Printf("  1sec config set server.port 8080\n")
		fmt.Printf("  1sec config set logging.level debug --profile prod\n")
	case "check":
		fmt.Printf("%s\n\n", bold("1sec check"))
		fmt.Printf("Run pre-flight diagnostics to verify the system is ready.\n\n")
		fmt.Printf("Checks config validity, port availability, data directory, AI keys,\n")
		fmt.Printf("port conflicts, syslog, and Rust engine binary.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
	case "logs":
		fmt.Printf("%s\n\n", bold("1sec logs"))
		fmt.Printf("Fetch recent log entries from a running 1SEC instance.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--lines <n>", "Number of log lines to fetch (default: 50)")
		fmt.Printf("  %-28s  %s\n", "-f, --follow", "Continuously poll for new entries (like tail -f)")
		fmt.Printf("  %-28s  %s\n", "--poll-interval <duration>", "Poll interval for --follow mode (default: 2s)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec logs\n")
		fmt.Printf("  1sec logs --lines 100\n")
		fmt.Printf("  1sec logs --follow\n")
		fmt.Printf("  1sec logs -f --poll-interval 1s\n")
		fmt.Printf("  1sec logs --format json --output engine.log\n")
	case "events":
		fmt.Printf("%s\n\n", bold("1sec events"))
		fmt.Printf("Submit a security event to a running 1SEC instance.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--input <file>", "Read event JSON from file (- for stdin)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  echo '{\"type\":\"login_failure\",\"source_ip\":\"1.2.3.4\"}' | 1sec events\n")
		fmt.Printf("  1sec events --input event.json\n")
	case "export":
		fmt.Printf("%s\n\n", bold("1sec export"))
		fmt.Printf("Export alerts or events in bulk for compliance reporting.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--type <type>", "What to export: alerts, events (default: alerts)")
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: json, csv, sarif (default: json)")
		fmt.Printf("  %-28s  %s\n", "--output <file>", "Write to file (default: stdout)")
		fmt.Printf("  %-28s  %s\n", "--severity <level>", "Minimum severity filter")
		fmt.Printf("  %-28s  %s\n", "--module <name>", "Filter by module")
		fmt.Printf("  %-28s  %s\n", "--limit <n>", "Maximum records (default: 1000)")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec export --format csv --output alerts.csv\n")
		fmt.Printf("  1sec export --format sarif --output results.sarif\n")
		fmt.Printf("  1sec export --type events --format json\n")
		fmt.Printf("  1sec export --severity HIGH --module injection_shield\n")
	case "profile":
		fmt.Printf("%s\n\n", bold("1sec profile"))
		fmt.Printf("Manage named configuration profiles for different environments.\n")
		fmt.Printf("Profiles are stored in ~/.1sec/profiles/<name>.yaml\n\n")
		fmt.Printf("%s\n\n", bold("SUBCOMMANDS"))
		fmt.Printf("  %-20s  %s\n", "list", "List all profiles")
		fmt.Printf("  %-20s  %s\n", "create <name>", "Create a new profile")
		fmt.Printf("  %-20s  %s\n", "show <name>", "Show profile details")
		fmt.Printf("  %-20s  %s\n", "delete <name>", "Delete a profile")
		fmt.Printf("  %-20s  %s\n", "use <name>", "Set as default profile")
		fmt.Printf("\n%s\n\n", bold("CREATE FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--from <file>", "Copy config from existing file")
		fmt.Printf("  %-28s  %s\n", "--minimal", "Generate minimal config")
		fmt.Printf("  %-28s  %s\n", "--description <text>", "Profile description")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec profile list\n")
		fmt.Printf("  1sec profile create prod --from configs/production.yaml\n")
		fmt.Printf("  1sec profile create dev --minimal\n")
		fmt.Printf("  1sec profile use prod\n")
		fmt.Printf("  1sec status --profile prod\n")
	case "dashboard":
		fmt.Printf("%s\n\n", bold("1sec dashboard"))
		fmt.Printf("Launch a live TUI dashboard showing real-time engine status,\n")
		fmt.Printf("module health, and recent alerts. Like htop for 1SEC.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--refresh <duration>", "Refresh interval (default: 3s)")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec dashboard\n")
		fmt.Printf("  1sec dashboard --refresh 1s\n")
		fmt.Printf("  1sec dashboard --profile prod\n")
	case "stop":
		fmt.Printf("%s\n\n", bold("1sec stop"))
		fmt.Printf("Gracefully stop a running 1SEC instance via the API.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("  %-28s  %s\n", "--timeout <duration>", "Request timeout (default: 5s)")
	case "init":
		fmt.Printf("%s\n\n", bold("1sec init"))
		fmt.Printf("Generate a starter configuration file with sensible defaults.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--output <path>", "Output file path (default: 1sec.yaml)")
		fmt.Printf("  %-28s  %s\n", "--minimal", "Generate a minimal config (only essential settings)")
		fmt.Printf("  %-28s  %s\n", "--force", "Overwrite existing file without prompting")
	case "docker":
		fmt.Printf("%s\n\n", bold("1sec docker"))
		fmt.Printf("Manage the 1SEC Docker Compose deployment.\n\n")
		fmt.Printf("%s\n\n", bold("SUBCOMMANDS"))
		fmt.Printf("  %-20s  %s\n", "up", "Start 1SEC via Docker Compose (detached)")
		fmt.Printf("  %-20s  %s\n", "down", "Stop and remove containers")
		fmt.Printf("  %-20s  %s\n", "logs", "Follow container logs")
		fmt.Printf("  %-20s  %s\n", "status", "Show container status")
		fmt.Printf("  %-20s  %s\n", "build", "Build the Docker image from source")
		fmt.Printf("  %-20s  %s\n", "pull", "Pull the latest image from registry")
	case "completions":
		fmt.Printf("%s\n\n", bold("1sec completions"))
		fmt.Printf("Generate shell completion scripts.\n\n")
		fmt.Printf("%s\n\n", bold("SHELLS"))
		fmt.Printf("  %-12s  %s\n", "bash", "Generate Bash completions")
		fmt.Printf("  %-12s  %s\n", "zsh", "Generate Zsh completions")
		fmt.Printf("  %-12s  %s\n", "fish", "Generate Fish completions")
		fmt.Printf("  %-12s  %s\n", "powershell", "Generate PowerShell completions")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  %s\n", dim("# Bash (add to ~/.bashrc)"))
		fmt.Printf("  source <(1sec completions bash)\n\n")
		fmt.Printf("  %s\n", dim("# Zsh (add to ~/.zshrc)"))
		fmt.Printf("  source <(1sec completions zsh)\n\n")
		fmt.Printf("  %s\n", dim("# Fish"))
		fmt.Printf("  1sec completions fish | source\n\n")
		fmt.Printf("  %s\n", dim("# PowerShell"))
		fmt.Printf("  1sec completions powershell | Out-String | Invoke-Expression\n")
	case "correlator":
		fmt.Printf("%s\n\n", bold("1sec correlator"))
		fmt.Printf("Inspect the threat correlator state — active source windows,\n")
		fmt.Printf("attack chain definitions, and cross-module correlation status.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec correlator\n")
		fmt.Printf("  1sec correlator --json\n")
		fmt.Printf("  1sec correlator --profile prod\n")
	case "threats":
		fmt.Printf("%s\n\n", bold("1sec threats"))
		fmt.Printf("Query dynamic IP threat scoring — shows tracked IPs, their\n")
		fmt.Printf("accumulated threat points, contributing modules, and block status.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json, csv")
		fmt.Printf("  %-28s  %s\n", "--blocked", "Show only blocked IPs")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec threats\n")
		fmt.Printf("  1sec threats --blocked\n")
		fmt.Printf("  1sec threats --json\n")
		fmt.Printf("  1sec threats --format csv --output threats.csv\n")
	case "rust":
		fmt.Printf("%s\n\n", bold("1sec rust"))
		fmt.Printf("Check the Rust sidecar engine status — running state, config,\n")
		fmt.Printf("worker count, pattern matching settings, and packet capture.\n\n")
		fmt.Printf("%s\n\n", bold("FLAGS"))
		fmt.Printf("  %-28s  %s\n", "--format <fmt>", "Output format: table, json")
		fmt.Printf("  %-28s  %s\n", "--profile <name>", "Named profile to use")
		fmt.Printf("\n%s\n\n", bold("EXAMPLES"))
		fmt.Printf("  1sec rust\n")
		fmt.Printf("  1sec rust --json\n")
	default:
		fmt.Fprintf(os.Stderr, red("error: ")+"unknown command %q — run '1sec help' for usage\n", subcmd)
		os.Exit(1)
	}
}
