package main

// ---------------------------------------------------------------------------
// cmd_init.go — generate a starter configuration file
// ---------------------------------------------------------------------------

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func cmdInit(args []string) {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	output := fs.String("output", "1sec.yaml", "Output file path")
	minimal := fs.Bool("minimal", false, "Generate minimal config")
	force := fs.Bool("force", false, "Overwrite existing file")
	fs.Parse(args)

	if !*force {
		if _, err := os.Stat(*output); err == nil {
			errorf("file %q already exists — use --force to overwrite", *output)
		}
	}

	dir := filepath.Dir(*output)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			errorf("creating directory %q: %v", dir, err)
		}
	}

	var content string
	if *minimal {
		content = minimalConfig()
	} else {
		content = fullConfig()
	}

	if err := os.WriteFile(*output, []byte(content), 0644); err != nil {
		errorf("writing config: %v", err)
	}

	fmt.Fprintf(os.Stdout, "%s Configuration written to %s\n", green("✓"), *output)
	fmt.Fprintf(os.Stdout, "%s Run '1sec up --config %s' to start\n", dim("▸"), *output)
}

func minimalConfig() string {
	return `# 1SEC Configuration (minimal)
# See 'configs/default.yaml' for all options or run '1sec init' without --minimal.

server:
  host: "0.0.0.0"
  port: 1780
  # api_keys:
  #   - "your-secret-key-here"

logging:
  level: "info"
  format: "console"

# All 16 modules are enabled by default.
# Disable specific modules:
# modules:
#   iot_shield:
#     enabled: false
`
}

func fullConfig() string {
	return `# 1SEC Configuration
# Generated by '1sec init'. All modules enabled with sane defaults.
# Docs: https://github.com/1sec-project/1sec

server:
  host: "0.0.0.0"
  port: 1780
  # API key authentication — set one or more keys to secure the REST API.
  # If empty, the API runs in open mode (no auth required).
  # Can also be set via ONESEC_API_KEY environment variable.
  # api_keys:
  #   - "your-secret-api-key-here"
  #
  # CORS — restrict allowed origins for the REST API.
  # cors_origins:
  #   - "https://your-dashboard.example.com"

bus:
  url: "nats://127.0.0.1:4222"
  embedded: true
  data_dir: "./data/nats"
  port: 4222
  cluster_id: "1sec-cluster"

alerts:
  max_store: 10000
  enable_console: true
  # webhook_urls:
  #   - "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

syslog:
  enabled: false
  protocol: "udp"    # "udp", "tcp", or "both"
  host: "0.0.0.0"
  port: 1514

logging:
  level: "info"       # debug, info, warn, error
  format: "console"   # console, json

modules:
  network_guardian:
    enabled: true
    settings:
      max_requests_per_minute: 1000
      burst_size: 100

  api_fortress:
    enabled: true
    settings:
      api_max_rpm: 200

  iot_shield:
    enabled: true

  injection_shield:
    enabled: true

  supply_chain:
    enabled: true

  ransomware:
    enabled: true
    settings:
      encryption_threshold: 10
      exfil_mb_threshold: 100

  auth_fortress:
    enabled: true
    settings:
      max_failures_per_minute: 10
      lockout_duration_seconds: 300
      stuffing_threshold: 50

  deepfake_shield:
    enabled: true

  identity_monitor:
    enabled: true

  llm_firewall:
    enabled: true
    settings:
      token_budget_per_hour: 100000

  ai_containment:
    enabled: true

  data_poisoning:
    enabled: true

  quantum_crypto:
    enabled: true

  runtime_watcher:
    enabled: true
    settings:
      scan_interval_seconds: 300

  cloud_posture:
    enabled: true

  ai_analysis_engine:
    enabled: true
    settings:
      # gemini_api_key: "YOUR_GEMINI_API_KEY"
      # Also reads from env: GEMINI_API_KEY
      triage_model: "gemini-flash-lite-latest"
      deep_model: "gemini-flash-latest"
      api_base_url: "https://generativelanguage.googleapis.com/v1beta/models"
      triage_workers: 4
      deep_workers: 2

rust_engine:
  enabled: false
  binary: "1sec-engine"
  workers: 0               # 0 = auto-detect CPU cores
  buffer_size: 10000
  min_score: 0.0
  aho_corasick_prefilter: true
  capture:
    enabled: false
    interface: "eth0"
    bpf_filter: ""
    promiscuous: true
`
}
