//! Event types — mirrors the Go `core.SecurityEvent` and `core.Alert` structs
//! so the Rust engine can deserialize events from NATS and publish results back.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Mirrors `core.SecurityEvent` from the Go codebase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityEvent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub module: String,
    #[serde(rename = "type")]
    pub event_type: String,
    pub severity: Severity,
    pub source: EventSource,
    pub data: serde_json::Value,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub description: String,
}

/// Event source information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventSource {
    #[serde(default)]
    pub ip: String,
    #[serde(default)]
    pub port: u16,
    #[serde(default)]
    pub hostname: String,
    #[serde(default)]
    pub service: String,
}

/// Severity levels — matches Go's `core.Severity` iota values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Low,
    Medium,
    High,
    Critical,
}

impl Severity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Info => "info",
            Severity::Low => "low",
            Severity::Medium => "medium",
            Severity::High => "high",
            Severity::Critical => "critical",
        }
    }

    pub fn score(&self) -> f64 {
        match self {
            Severity::Info => 0.1,
            Severity::Low => 0.3,
            Severity::Medium => 0.5,
            Severity::High => 0.7,
            Severity::Critical => 0.9,
        }
    }
}

/// Result of pattern matching against an event — published back to NATS.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchResult {
    pub event_id: String,
    pub timestamp: DateTime<Utc>,
    pub matches: Vec<PatternMatch>,
    pub aggregate_score: f64,
    pub highest_severity: Severity,
    pub processing_time_us: u64,
}

/// A single pattern match within an event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PatternMatch {
    pub pattern_name: String,
    pub category: String,
    pub severity: Severity,
    pub matched_text: String,
    pub field: String,
    pub offset: usize,
}

/// Packet event — generated by the Rust packet capture engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PacketEvent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub protocol: String,
    pub src_ip: String,
    pub src_port: u16,
    pub dst_ip: String,
    pub dst_port: u16,
    pub length: usize,
    pub flags: Vec<String>,
    #[serde(default)]
    pub payload_preview: String,
    #[serde(default)]
    pub anomalies: Vec<String>,
}
